Iter13
spqrcor/shortener pull request #14
Opened 2024-08-08 20:43 UTC by spqrcor

2024-08-12 09:22 UTC, tmvrus requested changes
- контекст входящего запроса не используется
- storage если возвращает ошибки, они превращаются в BadRequest, если сломалась связь до БД, разве это должен быть BadRequest?

2024-08-12 09:22 UTC, tmvrus commented on internal/app/utils.go
> +}
эта ф-я хороший пример смешения обязанностей - проверка входящего url и генерация нового, `generateShortURL` никак не зависит от входящего параметра, зачем тогда смешивать эти два процесса

2024-08-12 09:22 UTC, tmvrus commented on internal/db/connector.go
> +		return nil, err
Fatal немедленно завершает работу приложения, писать после этого return никакого смысла нет.  Возможно стоит заменить Fatal на Error ?

2024-08-12 09:22 UTC, tmvrus commented on internal/handlers/handlers.go
> +	genURL, err := storage.Source.Add(context.Background(), string(bodyBytes))
А по какой причине берется пустой контекст вместо контекста запроса?

2024-08-12 09:22 UTC, tmvrus commented on internal/handlers/handlers.go
> +	_, err := buf.ReadFrom(body)
переменная body точно нужна?

2024-08-12 16:10 UTC, spqrcor commented on internal/app/utils.go
> +}
Хотел немного сократить код, но согласен, выглядит нелогично

2024-08-12 16:18 UTC, spqrcor commented
> * контекст входящего запроса не используется
> * storage если возвращает ошибки, они превращаются в BadRequest, если сломалась связь до БД, разве это должен быть BadRequest?

По возврату ошибки, я пробежался по заданиям спринта и негде не увидел это в заданиях, есть только такое

![image](https://github.com/user-attachments/assets/993dfbdd-2482-4f7b-8ac7-b3df9a6a5c20)

и там 500 выдается

2024-08-13 08:54 UTC, tmvrus commented
> > * контекст входящего запроса не используется
> > * storage если возвращает ошибки, они превращаются в BadRequest, если сломалась связь до БД, разве это должен быть BadRequest?
> 
> По возврату ошибки, я пробежался по заданиям спринта и негде не увидел это в заданиях, есть только такое
> 
> ![image](https://private-user-images.githubusercontent.com/4481660/357124342-993dfbdd-2482-4f7b-8ac7-b3df9a6a5c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzk1MjYsIm5iZiI6MTcyMzUzOTIyNiwicGF0aCI6Ii80NDgxNjYwLzM1NzEyNDM0Mi05OTNkZmJkZC0yNDgyLTRmN2ItOGFjNy1iM2RmOWE2YTVjMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDg1MzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhmYzdmNTA1NmY5NmY2MDM1NWFmMGU1Yjg3OGViNjc4YzU2ZTk0NjBlZWExOGUwODgwMDBjOWYzZjkyYjBmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._bF4mbqeW702IEQwV57XNbnRVzgZzA1C14MMbyjj0b0)
> 
> и там 500 выдается

ну кроме заданий спринта есть описание того как работает HTTP протокол и какой статус за что отвечает, рекомендую ознакомиться

2024-08-13 08:55 UTC, tmvrus approved these changes

2024-08-13 14:33 UTC, spqrcor commented
> > > * контекст входящего запроса не используется
> > > * storage если возвращает ошибки, они превращаются в BadRequest, если сломалась связь до БД, разве это должен быть BadRequest?
> > 
> > 
> > По возврату ошибки, я пробежался по заданиям спринта и негде не увидел это в заданиях, есть только такое
> > ![image](https://private-user-images.githubusercontent.com/4481660/357124342-993dfbdd-2482-4f7b-8ac7-b3df9a6a5c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzk1MjYsIm5iZiI6MTcyMzUzOTIyNiwicGF0aCI6Ii80NDgxNjYwLzM1NzEyNDM0Mi05OTNkZmJkZC0yNDgyLTRmN2ItOGFjNy1iM2RmOWE2YTVjMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDg1MzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhmYzdmNTA1NmY5NmY2MDM1NWFmMGU1Yjg3OGViNjc4YzU2ZTk0NjBlZWExOGUwODgwMDBjOWYzZjkyYjBmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._bF4mbqeW702IEQwV57XNbnRVzgZzA1C14MMbyjj0b0)
> > и там 500 выдается
> 
> ну кроме заданий спринта есть описание того как работает HTTP протокол и какой статус за что отвечает, рекомендую ознакомиться

поправил

2024-08-13 14:33 UTC, merged